spring.application.name=honda_manual_bot

telegram.bot.username=honda_crv_2024_manual_bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-5.4
openai.vector-store-id=${OPENAI_VECTOR_STORE_ID}
